// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gdadgggigqgnyqawzonc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdkYWRnZ2dpZ3FnbnlxYXd6b25jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMzkwNTIsImV4cCI6MjA2NjgxNTA1Mn0.kEyCe0-jKORC95iELhcqaO-KXRzdUm6_V_EEW3bCM7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});